### ISSUE TITLE
Honor `prefers-reduced-motion` user setting for accessibility 

### ISSUE THREAD

**Issue by adam-at-brown** [Etesam913/react-magic-motion#4]
For accessibility purposes, skip/cancel all animations when a user has a `reduce` preference set for `prefers-reduced-motion`.

Reference https://www.w3.org/WAI/WCAG22/Techniques/css/C39.html

**Comment by Etesam913** [comment]
The `<MagicMotion>` and the `<MagicCard>` components now respect this user setting.

https://github.com/Etesam913/react-magic-motion/releases/tag/v1.0.8
